name: task_products
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:

  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  flutter_staggered_grid_view: ^0.7.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_carousel_slider: ^1.1.0
  carousel_slider: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  formz: ^0.7.0
  get_it: ^7.7.0
  image_picker: ^1.1.0
  internet_connection_checker_plus: ^2.3.0
  intl: ^0.19.0
  lottie: ^3.1.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  skeletonizer: ^1.4.2
  badges: ^3.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  bottom_navy_bar: ^6.0.0
  flutter_svg: ^2.0.10+1


dev_dependencies:
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter_assets:
  assets_path: assets/
  output_path: lib/core/resources_manager
  filename: assets.dart
flutter:
  uses-material-design: true
  assets:
    - assets/img/png/
    - assets/img/svg/
    - assets/fonts/
    - assets/translations/
    - assets/json/


    
  fonts:
    - family: Sst_arabic
      fonts:
        - asset: assets/fonts/sst-roman.ttf
          weight: 400
        - asset: assets/fonts/sst-light.ttf
          weight: 300 
        - asset: assets/fonts/sst-medium.ttf
          weight: 500
        - asset: assets/fonts/sst-bold.ttf
          weight: 700
         
   
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cabin-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cabin-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cabin-Regular.ttf
          weight: 400      
